steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'buildx',
        'build',
        '--platform',
        'linux/amd64',
        '-t',
        'asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}',
        '.',
      ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}',
      ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}'
      - '--region'
      - '${_SERVICE_REGION}'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
