version: "3"

services: 
  postgres:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-jokedb}
      PGDATA: /data/postgres 
    networks:
      - postgres
    restart: always
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

networks:
  postgres:
    driver: bridge
  api:
    driver: bridge

volumes:
  postgres:
